# Generated by Django 4.2.4 on 2023-08-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIevent',
            fields=[
                ('Sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Event', models.CharField(max_length=30)),
                ('Branch', models.CharField(max_length=30)),
                ('Year', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('Contact', models.CharField(max_length=10)),
                ('Team_Size', models.CharField(max_length=10)),
                ('Member1', models.CharField(max_length=30, null=True)),
                ('Member2', models.CharField(max_length=30, null=True)),
                ('Member3', models.CharField(max_length=30, null=True)),
                ('Member4', models.CharField(max_length=30, null=True)),
                ('Transaction', models.ImageField(upload_to='Event/images')),
            ],
        ),
    ]
