# Generated by Django 4.2.4 on 2023-08-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIverse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIverse',
            fields=[
                ('Sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Event', models.CharField(max_length=30)),
                ('Branch', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('Contact', models.CharField(max_length=10)),
                ('Team_Size', models.CharField(max_length=10)),
                ('team_member', models.CharField(max_length=100, null=True)),
                ('Transaction', models.ImageField(upload_to='Event/images')),
            ],
        ),
        migrations.DeleteModel(
            name='AIevent',
        ),
    ]
