# Generated by Django 4.2.4 on 2023-08-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIverse', '0002_aiverse_delete_aievent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiverse',
            name='Transaction',
            field=models.ImageField(null=True, upload_to='Event/images'),
        ),
    ]
